name: markdown-link-check
on:
  push:
jobs:
  markdown-link-check:
    name: Check markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [markdown-link-check]
    if: always() && (needs.markdown-link-check.result == 'failure')
    steps:
      # email
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} failed!
          html_body: file://README.md
          to: karl-august.kongo@khk.ee
          from: github-actions
