name: Hello

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!

      - name: Send mail
          uses: dawidd6/action-send-mail@v3
          with:
            # Required mail server address:
            server_address: smtp.hotmail.com port
            # Required mail server port:
            server_port: 587
            # Required mail subject:
            subject: Github Actions job result
            # Required recipients' addresses:
            to: karlaugustkk@hotmail.com,doejohn@gmail.com
            # Required sender full name (address can be skipped):
            from: Luke Skywalker # <user@example.com>

